<a href="https://colab.research.google.com/github/irostylemina/gitstudy/blob/main/11%EC%A3%BC%EC%B0%A8_%EC%88%99%EC%A0%9C_2025163046_%EC%9E%84%EB%AF%B8%EB%82%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 설치 및 불러오기

In [10]:
import numpy as np

# 예제 코드 읽기

In [11]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

# 배열 기본 사항

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
print(a[0])

1


In [14]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [15]:
a[:3]

array([10,  2,  3])

In [16]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
print(a[1, 3])

8


# 배열 속성

In [19]:
a.ndim

2

In [20]:
a.shape
len(a.shape) == a.ndim

True

In [21]:
a.size
import math
a.size == math.prod(a.shape)

True

In [22]:
a.dtype

dtype('int64')

# 기본 배열을 만드는 방법

In [23]:
np.zeros(2)

array([0., 0.])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [26]:
np.arange(4)

array([0, 1, 2, 3])

In [27]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [28]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

# 요소 추가, 제거 및 정렬

In [30]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [31]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [33]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [35]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# 배열의 모양과 크기를 어떻게 알 수 있나요

In [36]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [37]:
array_example.ndim

3

In [38]:
array_example.size

24

In [39]:
array_example.shape

(3, 2, 4)

# 배열의 형태를 바꿀 수 있나요

In [40]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [41]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [42]:
np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

# 1차원 배열을 2차원 배열로 변환하는 방법 (배열에 새 축을 추가하는 방법

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [44]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [45]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [46]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [47]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [48]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# 인덱싱 및 슬라이싱

In [49]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [51]:
print(a[a < 5])

[1 2 3 4]


In [52]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [53]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [54]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [55]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [56]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [57]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [58]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [59]:
print(a[b])

[1 2 3 4]


In [60]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# 기존 데이터를 이용해 배열을 만드는 방법

In [61]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [63]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [64]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [65]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [66]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [68]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [69]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [70]:
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
b2 = a.copy()

# 기본 배열 연산

In [72]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [73]:
data - ones
data * data
data / data

array([1., 1.])

In [74]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [75]:
b = np.array([[1, 1], [2, 2]])

In [76]:
b.sum(axis=0)

array([3, 3])

In [77]:
b.sum(axis=1)

array([2, 4])

# 방송

In [78]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# 더 유용한 배열 연산

In [79]:
data = np.array([1, 2, 3])
data.max()
data.min()
data.sum()

np.int64(6)

In [80]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [81]:
a.sum()

np.float64(4.8595784)

In [82]:
a.min()

np.float64(0.05093587)

In [83]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# 행렬 생성

In [84]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
data[0, 1]

np.int64(2)

In [86]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [87]:
data[0:2, 0]

array([1, 3])

In [88]:
data.max()

np.int64(6)

In [89]:
data.min()

np.int64(1)

In [90]:
data.sum()

np.int64(21)

In [91]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [92]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [93]:
data.max(axis=0)

array([5, 6])

In [94]:
data.max(axis=1)

array([2, 5, 6])

In [95]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [96]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [97]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [98]:
np.ones(3)

array([1., 1., 1.])

In [99]:
np.zeros(3)

array([0., 0., 0.])

In [100]:
rng = np.random.default_rng()  # the simplest way to generate random numbers

In [101]:
rng.random(3)

array([0.19044725, 0.96706647, 0.87254689])

In [102]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [103]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [104]:
rng.random((3, 2))

array([[3.70503231e-01, 4.43973246e-01],
       [9.31619332e-01, 8.75595934e-04],
       [1.38589728e-01, 3.05251063e-01]])

# 난수 생성 중

In [105]:
rng.integers(5, size=(2, 4))

array([[0, 0, 2, 3],
       [2, 0, 3, 4]])

# 고유 아이템과 개수를 얻는 방법

In [106]:
import numpy as np

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)

print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [107]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [108]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [109]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [110]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [111]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [112]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


# 행렬의 전치 및 변형

In [113]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [117]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# 배열을 역순으로 만드는 방법

In [118]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
reversed_arr = np.flip(arr)

In [120]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [121]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [122]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [123]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [124]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [125]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [126]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]
